# -*- coding: utf-8 -*-
"""IDS_using_Machine_Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0v0vLmN6BbVRefE1IG3rOKWztYhOH9Z
"""

# --- KHỐI 1: TẢI VÀ GỘP NHIỀU FILE ---
import pandas as pd
import numpy as np

# 1. Danh sách các file huấn luyện chung
# Để file csv cùng thư mục với file .py hoặc .ipynb
file_paths = [
    'Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv',
    'Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv',
    'Tuesday-WorkingHours.pcap_ISCX.csv',
]

dataframes_list = []

print(f"--- Bắt đầu quy trình gộp {len(file_paths)} file dữ liệu ---")

try:
    for path in file_paths:
        print(f"\nĐang xử lý file: {path.split('/')[-1]}...")

        # Đọc file
        df_temp = pd.read_csv(path)

        # --- DỌN DẸP NGAY LẬP TỨC (để tiết kiệm RAM) ---

        # 1. Sửa tên cột (xóa khoảng trắng)
        df_temp.columns = df_temp.columns.str.strip()

        # 2. Xử lý dữ liệu bẩn
        df_temp.replace([np.inf, -np.inf], np.nan, inplace=True)
        df_temp.dropna(inplace=True)

        # 3. Mã hóa nhãn (Label)
        df_temp['is_attack'] = df_temp['Label'].apply(lambda x: 0 if x == 'BENIGN' else 1)
        df_temp.drop('Label', axis=1, inplace=True)

        # --- LẤY MẪU (SAMPLING) ---
        # Chỉ lấy 20% dữ liệu của mỗi file để tránh tràn RAM Colab
        df_sample = df_temp.sample(frac=0.2, random_state=42)

        print(f"-> Gốc: {len(df_temp)} hàng. Đã lấy mẫu: {len(df_sample)} hàng.")
        print(f"-> Số lượng tấn công trong mẫu: {df_sample['is_attack'].sum()}")

        # Thêm vào danh sách chờ
        dataframes_list.append(df_sample)

        # Xóa biến tạm để giải phóng RAM
        del df_temp

    df = pd.concat(dataframes_list, ignore_index=True)

    print(f"Tổng số hàng dữ liệu: {len(df)}")
    print(df['is_attack'].value_counts())


except KeyError as e:
    print(f"LỖI TÊN CỘT: {e}. Có thể một trong các file có tên cột khác biệt.")
except FileNotFoundError as e:
    print(f"LỖI KHÔNG TÌM THẤY FILE: {e}. Kiểm tra lại đường dẫn.")
except Exception as e:
    print(f"LỖI KHÁC: {e}")

# --- KHỐI 2: TÁCH X/y VÀ CHUẨN HÓA ---

# Import thư viện StandardScaler
from sklearn.preprocessing import StandardScaler

if 'df' in locals():

    # 2a. Tách Đặc trưng (X) và Mục tiêu (y)
    y = df['is_attack']
    X = df.drop('is_attack', axis=1)

    print(f"Đã tách X (Kích thước: {X.shape}) và y (Kích thước: {y.shape}).")

    # 2b. Chuẩn hóa (Scaling) Đặc trưng X
    print("Đang chuẩn hóa X...")

    # Tạo một đối tượng StandardScaler
    scaler = StandardScaler()

    # Học (fit) và biến đổi (transform) X
    X_scaled_array = scaler.fit_transform(X)

    # Chuyển mảng NumPy trở lại thành DataFrame
    X_scaled = pd.DataFrame(X_scaled_array, columns=X.columns)

    print("\n--- 5 hàng đầu của X ---")
    print(X_scaled.head())

else:
    print("LỖI: Vui lòng chạy Khối 1 trước để tạo DataFrame 'df'.")

# --- KHỐI 3: CHIA DỮ LIỆU TRAIN/TEST ---

# Import thư viện train_test_split
from sklearn.model_selection import train_test_split

if 'X_scaled' in locals() and 'y' in locals():

    # test_size=0.2 (20% test)
    # random_state=42 (để đảm bảo kết quả nhất quán)
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled,
        y,
        test_size=0.2,
        random_state=42
    )

    print("Chia dữ liệu hoàn tất!")
    print(f"X_train (đặc trưng huấn luyện): {X_train.shape}")
    print(f"y_train (mục tiêu huấn luyện): {y_train.shape}")
    print(f"X_test (đặc trưng kiểm tra):  {X_test.shape}")
    print(f"y_test (mục tiêu kiểm tra):  {y_test.shape}")

    # Lưu X_train, X_test, y_train, y_test để khối sau sử dụng

else:
    print("LỖI: Vui lòng chạy Khối 1 và Khối 2 trước.")

# --- KHỐI 4: TẠO VÀ HUẤN LUYỆN MÔ HÌNH RANDOM FOREST ---

# Import mô hình
from sklearn.ensemble import RandomForestClassifier

if 'X_train' in locals():

    # 4a. Tạo mô hình
    print("Đang tạo mô hình Random Forest...")
    # n_jobs=-1: Sử dụng tất cả CPU để chạy nhanh hơn
    model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)

    # 4b. Huấn luyện (fit) mô hình
    print("Đang huấn luyện mô hình...")
    model.fit(X_train, y_train)

    print("--- HUẤN LUYỆN HOÀN TẤT! ---")
    print("Mô hình đã được lưu vào biến 'model'.")

    # Lưu 'model' để khối sau sử dụng

else:
    print("LỖI: Vui lòng chạy Khối 1, 2, và 3 trước.")

# --- KHỐI 5: ĐÁNH GIÁ MÔ HÌNH RANDOM FOREST---

# Import các công cụ đánh giá
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

if 'model' in locals():

    # 5a. Yêu cầu mô hình dự đoán trên Test Set
    print("Đang dự đoán trên Test Set...")
    y_pred = model.predict(X_test)

    print("Dự đoán hoàn tất. Đang tính toán chỉ số...")

    # 5b. Tính toán các chỉ số
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    # --- 5c. In Kết quả ---
    print("\n--- === KẾT QUẢ ĐÁNH GIÁ MÔ HÌNH RANDOM FOREST === ---")
    print(f"Accuracy:  {accuracy * 100:.2f}%")
    print(f"Precision: {precision * 100:.2f}%")
    print(f"Recall:    {recall * 100:.2f}% (Chỉ số quan trọng nhất!)")
    print(f"F1-Score:  {f1 * 100:.2f}%")

    print("\n--- Ma trận nhầm lẫn (Confusion Matrix) ---")
    print("          (Dự đoán 0)   (Dự đoán 1)")
    print(f"Thực tế 0: {cm[0][0]:<12} {cm[0][1]:<12} (True Negative / False Positive)")
    print(f"Thực tế 1: {cm[1][0]:<12} {cm[1][1]:<12} (False Negative / True Positive)")

else:
    print("LỖI: Vui lòng chạy tất cả các khối trước đó.")

# --- KHỐI 6: TẠO VÀ HUẤN LUYỆN DECISION TREE ---

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, recall_score

if 'X_train' in locals():

    # 1. Tạo mô hình
    print("Đang tạo mô hình Decision Tree...")
    model_dt = DecisionTreeClassifier(random_state=42)

    # 2. Huấn luyện
    print("Đang huấn luyện (fit)...")
    model_dt.fit(X_train, y_train)

    # 3. Đánh giá nhanh
    y_pred_dt = model_dt.predict(X_test)
    rec_dt = recall_score(y_test, y_pred_dt)

    print(f"--- HUẤN LUYỆN XONG DECISION TREE ---")
    print(f"Recall sơ bộ: {rec_dt * 100:.2f}%")
    # Chúng ta lưu biến 'model_dt' để dùng cho Khối so sánh

else:
    print("LỖI: Vui lòng chạy các Khối 1, 2, 3 để có dữ liệu.")

# KHỐI 6.5: ĐÁNH GIÁ MÔ HÌNH DECISION TREE
# Import các công cụ đánh giá
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

if 'model_dt' in locals():

    # 6a. Yêu cầu mô hình dự đoán trên Test Set
    print("Đang dự đoán trên Test Set...")
    y_pred = model_dt.predict(X_test)

    print("Dự đoán hoàn tất. Đang tính toán chỉ số...")

    # 6b. Tính toán các chỉ số
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    # --- 6c. In Kết quả ---
    print("\n--- === KẾT QUẢ ĐÁNH GIÁ MÔ HÌNH DECISION TREE === ---")
    print(f"Accuracy:  {accuracy * 100:.2f}%")
    print(f"Precision: {precision * 100:.2f}%")
    print(f"Recall:    {recall * 100:.2f}% (Chỉ số quan trọng nhất!)")
    print(f"F1-Score:  {f1 * 100:.2f}%")

    print("\n--- Ma trận nhầm lẫn (Confusion Matrix) ---")
    print("          (Dự đoán 0)   (Dự đoán 1)")
    print(f"Thực tế 0: {cm[0][0]:<12} {cm[0][1]:<12} (True Negative / False Positive)")
    print(f"Thực tế 1: {cm[1][0]:<12} {cm[1][1]:<12} (False Negative / True Positive)")

else:
    print("LỖI: Vui lòng chạy tất cả các khối trước đó.")

# --- KHỐI 7: TẠO VÀ HUẤN LUYỆN LOGISTIC REGRESSION ---

from sklearn.linear_model import LogisticRegression

if 'X_train' in locals():

    # 1. Tạo mô hình
    # max_iter=1000 để đảm bảo thuật toán có đủ thời gian tìm ra đáp án tối ưu
    print("Đang tạo mô hình Logistic Regression...")
    model_lr = LogisticRegression(random_state=42, max_iter=1000)

    # 2. Huấn luyện
    print("Đang huấn luyện (fit)...")
    model_lr.fit(X_train, y_train)

    # 3. Đánh giá nhanh
    y_pred_lr = model_lr.predict(X_test)
    rec_lr = recall_score(y_test, y_pred_lr)

    print(f"--- HUẤN LUYỆN XONG LOGISTIC REGRESSION ---")
    print(f"Recall sơ bộ: {rec_lr * 100:.2f}%")
    # Chúng ta lưu biến 'model_lr' để dùng cho Khối so sánh

else:
    print("LỖI: Vui lòng chạy các Khối 1, 2, 3 để có dữ liệu.")

# --- KHỐI 8: SO SÁNH TẤT CẢ CÁC MÔ HÌNH ---

import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Kiểm tra xem cả 3 mô hình đã được tạo chưa
if 'model' in locals() and 'model_dt' in locals() and 'model_lr' in locals():

    # Danh sách các mô hình cần so sánh
    models_list = [
        ("Random Forest", model),
        ("Decision Tree", model_dt),
        ("Logistic Regression", model_lr)
    ]

    results = []

    for name, clf in models_list:
        print(f"Đang đánh giá lại: {name}...")

        # Dự đoán trên tập Test
        y_pred = clf.predict(X_test)

        # Tính toán các chỉ số
        results.append({
            "Mô hình": name,
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred),
            "Recall": recall_score(y_test, y_pred),
            "F1-Score": f1_score(y_test, y_pred)
        })

    # Tạo DataFrame để hiển thị bảng
    df_results = pd.DataFrame(results)

    # Sắp xếp giảm dần theo Recall (quan trọng nhất)
    df_results = df_results.sort_values(by="Recall", ascending=False)

    print("\n" + "="*50)
    print(" BẢNG XẾP HẠNG HIỆU SUẤT (Sắp xếp theo Recall)")
    print("="*50)
    print(df_results.to_string(index=False))
    print("="*50)

    # Nhận xét nhanh
    best_recall = df_results.iloc[0]['Recall']
    best_name = df_results.iloc[0]['Mô hình']
    print(f"\nMô hình hiệu quả nhất: {best_name} với độ nhạy (Recall) là {best_recall*100:.2f}%")

else:
    print("LỖI: Bạn chưa chạy đủ các khối trước.")